### PR TITLE
Select tables with rows

### PR DESCRIPTION
**Pull request by aguillenv**
Part of #1989 

image

image

### CODE REVIEW

**Comment by dfellis** [comment]
Does this auto-run the query on click of the :mag: ?

**Comment by aguillenv** [comment]
> Does this auto-run the query on click of the 🔍 ?

Yes!

**Review by dfellis — APPROVED** [review]

**Comment by depombo** [comment]
nit - using eye instead of a magnifying glass icon? not sure though. I don't love either

**Review by depombo — APPROVED** [review]

**Comment by dfellis** [comment]
> nit - using eye instead of a magnifying glass icon? not sure though. I don't love either

I think the eyes might be a bit creepy all in a row?

**Review by yrobla — APPROVED** [review]

**Comment by aguillenv** [comment]
leaving a couple of options for a follow-up:

- Search icon:
image

- Eye outline
image

- Eye solid
image

- table icon 
image

- document search icon
image

- External icon
image

**Comment by aguillenv** [comment]
> and the icon only shows up if the table has a nonzero number of rows?

I forgot to add the conditional but it does now :)

**Comment by depombo** [comment]
> leaving a couple of options for a follow-up:
> 
> * Search icon:
>   image
> * Eye outline
>   image
> * Eye solid
>   image
> * table icon
>   image
> * document search icon
>   image
> * External link / open in new tab icon
>   image

I think I like the table icon best, thoughts @aguillenv @dfellis ?

**Pull request merged**
